### ISSUE TITLE
Migrating from `DTypePointer` to `UnsafePointer`

### ISSUE THREAD

**Issue by mmenendezg** [Mojo-Numerics-and-Algorithms-group/NuMojo#92]
The Mojo team has confirmed in the nightly[ changelog](https://github.com/modularml/mojo/blob/nightly/docs/changelog.md) that they will deprecate the `DTypePointer`, and they suggest migrating to `UnsafePointer`. 

They have also changed the methods of the `UnsafePointer`. 

This will require to change the way we initialize the pointers for the `data` of the `NDArray`s. 

I can help on the migration using `Max Nightly` for the `NDArray` struct.

**Comment by MadAlex1997** [comment]
@mmenendezg Has it been confirmed that it will make it to the main branch in the next Mojo update? They have changed direction regarding this several times.

**Comment by mmenendezg** [comment]
I've only seen the changelog on the nightly branch, but I guess we should wait until the changes are applied to the main branch.

**Comment by mmenendezg** [comment]
@MadAlex1997 It seems like `DTypePointer` has been completely deprecated  on the nightly version:

<img width="1403" alt="image" src="https://github.com/user-attachments/assets/c7ac45b9-877c-4ff3-9a33-544c9208275a">

**Comment by MadAlex1997** [comment]
@mmenendezg They have reverted things of that scale in the main updates before. Regardless we need them to decide what the API for SIMD data loading is, as there is still a debate between `SIMD[width=n].load(UnsafePointer,i)` and `UnsafePointer.load(i)`. 

We can do it correctly once instead of chasing 5 or 10 changes, each of which might take 30 minutes to multiple hours. This is why, in addition to version stability and access (ie magic being functional and easy to add packages to), until Mojo is much more stable we don't plan on making a build based on Mojo features between main releases.

We have discussed this on the [Numojo Discord](https://discord.gg/K6dgGJuq) you are welcome to join the conversation.

**Comment by shivasankarka** [comment]
The PR #108 migrates NuMojo from Mojo 24.4 to 24.5 and uses `UnsafePointer` now.
